### ISSUE TITLE
Run failed with errorr text.trimEnd is not a function

### ISSUE THREAD

**Issue by gedennis** [prettier/eslint-plugin-prettier#278]
**What version of `Eslint` are you using?**
6.8.0
**What version of `prettier` are you using?**
2.0.2
**What version of `eslint-plugin-prettier` are you using?**
2.1.3
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```
{
  "trailingComma": "all",
  "tabWidth": 2,
  "semi": true,
  "printWidth": 80,
  "singleQuote": true
}
```
```
{
  "env": {
    "commonjs": true,
    "es6": true,
    "node": true
  },
  "extends": ["airbnb-base", "prettier"],
  "plugins": ["prettier"],
  "globals": {
    "Atomics": "readonly",
    "SharedArrayBuffer": "readonly"
  },
  "parserOptions": {
    "ecmaVersion": 2018
  },
  "rules": {
    "no-console": 0,
    "prettier/prettier": ["error"]
  }
}
```
**What source code are you linting?**
node.js
**What did you expect to happen?**
can run ok
**What actually happened?**
```
npm run lint

> koa2-boilerplate@0.0.1 lint /Users/dennisge/personal/koa2-boilerplate
> eslint *.js --fix

TypeError: text.trimEnd is not a function
Occurred while linting /Users/dennisge/personal/koa2-boilerplate/app.js:1
    at attachComments (/Users/dennisge/personal/koa2-boilerplate/node_modules/prettier/index.js:14782:60)
    at coreFormat (/Users/dennisge/personal/koa2-boilerplate/node_modules/prettier/index.js:14809:23)
    at format (/Users/dennisge/personal/koa2-boilerplate/node_modules/prettier/index.js:15031:75)
    at formatWithCursor (/Users/dennisge/personal/koa2-boilerplate/node_modules/prettier/index.js:15047:12)
    at args (/Users/dennisge/personal/koa2-boilerplate/node_modules/prettier/index.js:50695:12)
    at Object.format (/Users/dennisge/personal/koa2-boilerplate/node_modules/prettier/index.js:50715:12)
    at Program (/Users/dennisge/personal/koa2-boilerplate/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:240:41)
    at listeners.(anonymous function).forEach.listener (/Users/dennisge/personal/koa2-boilerplate/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/dennisge/personal/koa2-boilerplate/node_modules/eslint/lib/linter/safe-emitte
```
I have used this config for a long time, but it failed now. I may think is an issue about the version of plugin. Please help to check. Thanks.

**Comment by BPScott** [comment]
What version of node are you using? That error looks like it throwed within prettier's code instead of within this plugin's code.

[Prettier v2 dropped support for anything less than node v10](https://prettier.io/blog/2020/03/21/2.0.0.html) and it looks like trimEnd() was added in v10.

If you're not yet on node 10 or greater, you'll have to use prettier v1.x until you upgrade to a supported node version.

**Comment by gedennis** [comment]
@BPScott Thanks, Ben. That is really the node version issue. I used the node version 8.10.0. Thanks.

**Comment by kenkoooo** [comment]
I faced the same problem with the Intellij's prettier plugin, and resolved it by updating Node. Thanks a lot!

**Comment by dasheck0** [comment]
Had the same issue as @kenkoooo Was using Node 8, because of a legacy project. Switched to Node 12 and the error was gone.
