### ISSUE TITLE
New issue since Prettier v3

### ISSUE THREAD

**Issue by RobertGemmaJr** [prettier/eslint-plugin-prettier#565]
**What version of `eslint` are you using?**

8.44.0

**What version of `prettier` are you using?**

Prettier is not installed locally as a tool, though the issue only started today. I believe it may have something to do with Prettier's v3 release

**What version of `eslint-plugin-prettier` are you using?**

4.2.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

**.eslintrc.js**
```js
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true,
    es6: true,
  },
  extends: ['eslint:recommended', 'plugin:react/recommended', 'prettier'],
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly',
  },
  overrides: [{ files: ['*.jsx', '*.js'] }],
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 2018,
    sourceType: 'module',
  },
  plugins: ['react', 'prettier'],
  settings: {
    react: {
      version: 'detect',
    },
  },
  rules: {
    'react/prop-types': 'off',
    'prettier/prettier': 'warn',
  },
};
```

**.prettierrc.js**
```js
module.exports = {
  trailingComma: 'es5', // Add a trailing comma to all es5 modules
  singleQuote: true, // Use single quote (') for strings instead of doubles ("")
  jsxSingleQuote: true, // Use single quote (') for strings instead of doubles ("") in JSX files
  printWidth: 100, // Sets the maximum line size to 100 (default is 80)
  endOfLine: 'auto', // Configure the end of line character (/n) | REQUIRED FOR OS COMPATIBILITY
};
```

**What source code are you linting?**

The whole project? Running `npm run format` which runs `eslint --fix .`.

However, the error is occurring BEFORE it's linting any source code. It's an issue with the plugin itself.

**What did you expect to happen?**

Linting of files began

**What actually happened?**

Getting a `TypeError` on the first line of `.eslintrc.js` (My project doesn't use typescript):

```sh
> eslint --fix .


Oops! Something went wrong! :(

ESLint: 8.44.0

TypeError: prettier.resolveConfig.sync is not a function
Occurred while linting C:\Users\Rob\ROOT\CCV\ArcherTask\.eslintrc.js:1
Rule: "prettier/prettier"
    at Program (C:\Users\Rob\ROOT\CCV\ArcherTask\node_modules\eslint-plugin-prettier\eslint-plugin-prettier.js:138:40)
    at ruleErrorHandler (C:\Users\Rob\ROOT\CCV\ArcherTask\node_modules\eslint\lib\linter\linter.js:1050:28)
    at C:\Users\Rob\ROOT\CCV\ArcherTask\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\Rob\ROOT\CCV\ArcherTask\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Users\Rob\ROOT\CCV\ArcherTask\node_modules\eslint\lib\linter\node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (C:\Users\Rob\ROOT\CCV\ArcherTask\node_modules\eslint\lib\linter\node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (C:\Users\Rob\ROOT\CCV\ArcherTask\node_modules\eslint\lib\linter\node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (C:\Users\Rob\ROOT\CCV\ArcherTask\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:795:23)
```

**Comment by meshde** [comment]
Facing the same with prettier 3.0.0, eslint 8.44.0 and eslint-plugin-prettier 4.2.1

**Comment by Pnlvfx** [comment]
Same,  prettier as removed the resolveConfig.sync function as stated here: prettier.resolveConfigFile.sync is removed;

**Comment by kikoane** [comment]
Same with prettier 3.0.0, eslint 8.44.0 and eslint-plugin-prettier 4.2.1

**Comment by JounQin** [comment]
You need 5.0.0-alpha.1

**Comment by RobertGemmaJr** [comment]
@JounQin Thank you!! Does your team have an ETA as to when it will be officially released?

**Comment by tchetwin** [comment]
@RobertGemmaJr See: https://github.com/prettier/eslint-plugin-prettier/issues/562#issuecomment-1630329636 - this morning
