### ISSUE TITLE
Rule `"prettier/prettier": "error"` makes `eslint` fail

### ISSUE THREAD

**Issue by ThornWalli** [prettier/eslint-plugin-prettier#570]
**What version of `eslint` are you using?**
`8.42.0`

**What version of `prettier` are you using?**
`3.0.0`

**What version of `eslint-plugin-prettier` are you using?**
`5.0.0`

**What version of `node` are you using?**
`19.9.0`

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

`.eslintrc`
```json
{
  "root": true,
  "parserOptions": {
    "parser": "@babel/eslint-parser",
    "sourceType": "module",
    "requireConfigFile": false
  },
  "extends": [
    "@nuxtjs",
    "plugin:security/recommended",
    "plugin:sonarjs/recommended",
    "plugin:no-unsanitized/DOM",
    "plugin:jsonc/recommended-with-json",
    "prettier"
  ],
  "overrides": [
    {
      "files": [
        "*.code-workspace",
        "*.json",
        "*.json5",
        "*.jsonc"
      ],
      "parser": "jsonc-eslint-parser"
    }
  ],
  "plugins": [
    "no-secrets",
    "xss",
    "prettier"
  ],
  "rules": {
    "prettier/prettier": "error",
    "semi": [
      2,
      "always"
    ],
    "no-secrets/no-secrets": [
      "error"
    ],
    "xss/no-location-href-assign": 2,
    "xss/no-mixed-html": 0,
    "vue/no-v-html": "off",
    "vue/component-definition-name-casing": [
      "error",
      "PascalCase"
    ],
    "vue/component-name-in-template-casing": [
      "error",
      "kebab-case",
      {
        "registeredComponentsOnly": true,
        "ignores": []
      }
    ],
    "sonarjs/no-duplicate-string": 0,
    "vue/multi-word-component-names": "off",
    "@typescript-eslint/no-unused-vars": "off"
  }
}


```

`.prettierrc.js`
```js
export default {
  "arrowParens": "avoid",
  "bracketSameLine": true,
  "trailingComma": "none",
  "singleQuote": true,
  "semi": true,
  "printWidth": 80
};
```

**What source code are you linting?**

`.js,.mjs` and `.vue` Single-Files.

**What did you expect to happen?**

Updated the project to `prettier@3` along with additional dependencies `eslint-config-prettier` and `eslint-plugin-prettier`.

Start `eslint` and it will run successfully.

**What actually happened?**

I executed the command

```
$ node_modules/.bin/eslint --ext .js, .mjs, .vue .
```

I got this error:

```
Oops! Something went wrong! :(

ESLint: 8.42.0

AssertionError [ERR_ASSERTION]: Node must be provided when reporting error if location is not provided
    at assertValidNodeInfo (PROJECT_PATH/node_modules/eslint/lib/linter/report-translator.js:83:9)
    at PROJECT_PATH/node_modules/eslint/lib/linter/report-translator.js:317:9
    at Object.report (PROJECT_PATH/node_modules/eslint/lib/linter/linter.js:1021:41)
    at Program (PROJECT_PATH/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:204:23)
    at ruleErrorHandler (PROJECT_PATH/node_modules/eslint/lib/linter/linter.js:1050:28)
    at PROJECT_PATH/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (PROJECT_PATH/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (PROJECT_PATH/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (PROJECT_PATH/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
```

After that I reduced the `eslint` configuration:

```json
{
  "root": true,
  "parserOptions": {
    "ecmaVersion": "latest",
    "parser": "@babel/eslint-parser",
    "sourceType": "module",
    "requireConfigFile": false
  },
  "extends": [
    "prettier"
  ],
  "plugins": [
    "prettier"
  ],
  "rules": {
    "prettier/prettier": "error"
  }
}
```

still get the error.

Only when I remove the rule `"prettier/prettier": "error"` from the configuration, `eslint` runs again.

Thanks!

**Comment by JounQin** [comment]
Can you provide a runnable reproduction?

**Comment by ThornWalli** [comment]
I put a `console.log` on the `descriptor` of the `report-translator.js` (eslint).

![image](https://github.com/prettier/eslint-plugin-prettier/assets/8287751/55cedac7-7e2c-4a56-b616-5a437e679726)

**Comment by stclairdaniel** [comment]
I'm getting the same issue. eslint 8.44.0 and node 18.15.0

**Comment by ThornWalli** [comment]
I could solve it for me by simply renaming the `.prettierrc.js` to `.prettierrc.mjs`...

**Comment by JounQin** [comment]
@ThornWalli There is no `type: 'module'` in your `package.json`, so `.js` is intercepted as commonjs, then `export` is unexpected in `.prettierrc.js` file.

@stclairdaniel Please provide a reproduction.

**Comment by SkeLLLa** [comment]
Have the kind-a the same issue with `prettier/prettier` rule.

Error: unknown type: "ChainExpression"

Stack trace:
```
Rule: "prettier/prettier"
    at printPathNoParens (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:30038:17)
    at Object.genericPrint [as print] (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29629:23)
    at callPluginPrintFunction (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8550:22)
    at /xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8542:32
    at AstPath.call (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8359:24)
    at mainPrint (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8542:21)
    at printAssignment (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:26534:24)
    at printProperty (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:27274:14)
    at printPathNoParens (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29828:18)
    at Object.genericPrint [as print] (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29629:23)
    at callPluginPrintFunction (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8550:22)
    at mainPrint (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8537:18)
    at /xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:28234:22
    at AstPath.each (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8384:11)
    at printObject (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:28230:14)
    at printPathNoParens (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29822:18)
    at Object.genericPrint [as print] (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29629:23)
    at callPluginPrintFunction (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8550:22)
    at mainPrint (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8537:18)
    at /xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:26067:24
    at AstPath.each (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8384:11)
    at iterateCallArgumentsPath (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:22434:14)
    at printCallArguments (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:26065:7)
    at printMemberChain (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:26308:96)
    at printCallExpression (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:26465:16)
    at printPathNoParens (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29818:18)
    at Object.genericPrint [as print] (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29629:23)
    at callPluginPrintFunction (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8550:22)
    at /xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8542:32
    at AstPath.call (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8359:24)
    at mainPrint (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8542:21)
    at printPathNoParens (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29718:19)
    at Object.genericPrint [as print] (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29629:23)
    at callPluginPrintFunction (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8550:22)
    at mainPrint (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8537:18)
    at /xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:28754:25
    at AstPath.each (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8384:11)
    at printStatementSequence (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:28749:12)
    at printBody (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:28847:14)
    at printBlockBody (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:28979:20)
    at printBlock (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:28945:23)
    at printPathNoParens (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29809:18)
    at Object.genericPrint [as print] (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29629:23)
    at callPluginPrintFunction (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8550:22)
    at /xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8542:32
    at AstPath.call (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8359:24)
    at mainPrint (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8542:21)
    at printFunction (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:27372:177)
    at printPathNoParens (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29761:18)
    at Object.genericPrint [as print] (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29629:23)
    at callPluginPrintFunction (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8550:22)
    at /xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8542:32
    at AstPath.call (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8359:24)
    at mainPrint (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8542:21)
    at printAssignment (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:26534:24)
    at printProperty (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:27274:14)
    at printPathNoParens (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29828:18)
    at Object.genericPrint [as print] (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29629:23)
    at callPluginPrintFunction (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8550:22)
    at mainPrint (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8537:18)
    at /xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:28234:22
    at AstPath.each (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8384:11)
    at printObject (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:28230:14)
    at printPathNoParens (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29822:18)
    at Object.genericPrint [as print] (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29629:23)
    at callPluginPrintFunction (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8550:22)
    at mainPrint (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8537:18)
    at /xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:26067:24
    at AstPath.each (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8384:11)
    at iterateCallArgumentsPath (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:22434:14)
    at printCallArguments (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:26065:7)
    at printMemberChain (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:26308:96)
    at printCallExpression (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:26465:16)
    at printPathNoParens (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29818:18)
    at Object.genericPrint [as print] (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29629:23)
    at callPluginPrintFunction (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8550:22)
    at /xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8542:32
    at AstPath.call (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8359:24)
    at mainPrint (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8542:21)
    at printPathNoParens (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29776:29)
    at Object.genericPrint [as print] (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29629:23)
    at callPluginPrintFunction (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8550:22)
    at /xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8542:32
    at AstPath.call (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8359:24)
    at mainPrint (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8542:21)
    at printPathNoParens (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29718:19)
    at Object.genericPrint [as print] (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29629:23)
    at callPluginPrintFunction (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8550:22)
    at mainPrint (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8537:18)
    at /xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:28754:25
    at AstPath.each (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8384:11)
    at printStatementSequence (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:28749:12)
    at printBody (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:28847:14)
    at printBlockBody (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:28979:20)
    at printBlock (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:28945:23)
    at printPathNoParens (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29809:18)
    at Object.genericPrint [as print] (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29629:23)
    at callPluginPrintFunction (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8550:22)
    at /xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8542:32
    at AstPath.call (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8359:24)
    at mainPrint (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8542:21)
    at printFunction (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:27372:177)
    at printPathNoParens (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29761:18)
    at Object.genericPrint [as print] (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29629:23)
    at callPluginPrintFunction (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8550:22)
    at /xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8542:32
    at AstPath.call (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8359:24)
    at mainPrint (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8542:21)
    at printExportDeclaration (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:27987:25)
    at printPathNoParens (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29790:18)
    at Object.genericPrint [as print] (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29629:23)
    at callPluginPrintFunction (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8550:22)
    at mainPrint (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8537:18)
    at /xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:28754:25
    at AstPath.each (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8384:11)
    at printStatementSequence (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:28749:12)
    at printBody (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:28847:14)
    at printBlockBody (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:28979:20)
    at printPathNoParens (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29705:18)
    at Object.genericPrint [as print] (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:29629:23)
    at callPluginPrintFunction (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8550:22)
    at mainPrint (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8537:18)
    at printAstToDoc (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8529:18)
    at coreFormat (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:8837:20)
    at formatWithCursor2 (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:9021:18)
    at /xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:38183:12
    at Object.format (/xxx/node_modules/.pnpm/prettier@2.8.8/node_modules/prettier/index.js:38197:12)
    at Program (/xxx/node_modules/.pnpm/eslint-plugin-prettier@4.2.1_eslint-config-prettier@8.8.0_eslint@8.45.0_prettier@2.8.8/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:266:41)
    at ruleErrorHandler (/xxx/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/linter/linter.js:1050:28)
    at /xxx/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/xxx/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/xxx/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/xxx/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/xxx/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/xxx/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at /xxx/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/linter/linter.js:1085:32
    at Array.forEach (<anonymous>)
    at runRules (/xxx/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/linter/linter.js:1080:15)
    at Linter._verifyWithoutProcessors (/xxx/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/linter/linter.js:1330:31)
    at Linter._verifyWithConfigArray (/xxx/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/linter/linter.js:1706:21)
    at Linter.verify (/xxx/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/linter/linter.js:1412:65)
    at Linter.verifyAndFix (/xxx/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/linter/linter.js:1967:29)
    at verifyText (/xxx/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/cli-engine/cli-engine.js:254:48)
    at CLIEngine.executeOnFiles (/xxx/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/cli-engine/cli-engine.js:834:28)
    at ESLint.lintFiles (/xxx/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/eslint/eslint.js:551:23)
    at Object.execute (/xxx/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/lib/cli.js:391:36)
    at async main (/xxx/node_modules/.pnpm/eslint@8.45.0/node_modules/eslint/bin/eslint.js:135:24)
```

There's hard to provide any reproduction, since the error output is pretty useless and it points on a first line of a random file.
