### ISSUE TITLE
TypeError: Expected `input` to be a string, got `object`

### ISSUE THREAD

**Issue by colin-oos** [prettier/eslint-plugin-prettier#578]
**What version of `eslint` are you using?**

8.47.0

**What version of `prettier` are you using?**

3.0.2

**What version of `eslint-plugin-prettier` are you using?**

5.0.0

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**

```
// .prettierrc.js
module.exports = {
  bracketSpacing: true,
  jsxBracketSameLine: true,
  singleQuote: true,
  trailingComma: 'all',
  semi: false,
  tabWidth: 2,
  allowParens: 'avoid',
  printWidth: 120,
  parser: 'typescript',
  overrides: [
    {
      files: ['**/*.css', '**/*.scss', '**/*.html', '**/*.json'],
      options: {
        singleQuote: false,
      },
    },
  ],
}
```

```
// .eslintrc.js
module.exports = {
  env: {
    browser: true,
    es2021: true,
  },
  extends: ['prettier', 'eslint:recommended', 'plugin:react/recommended', 'plugin:@typescript-eslint/recommended'],
  overrides: [
    {
      files: ['*.ts', '*.tsx', '*.js'],
      rules: {
        semi: 0,
        'react-native/no-inline-styles': 0,
        'react-hooks/exhaustive-deps': 0,
        '@typescript-eslint/no-shadow': ['error'],
        'no-shadow': 'off',
        'no-undef': 'off',
        'prefer-const': 'off',
      },
    },
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  plugins: ['react', '@typescript-eslint', 'prettier'],
  rules: {
    'prettier/prettier': 'error',
    semi: ['error', 'never'],
    quotes: ['error', 'single'],
    'react/prop-types': 0,
  },
  ignorePatterns: ['**/*.json', '**/graphql/index.ts', '!.eslint.js', '!.prettierrc.js'],
}
```

**What source code are you linting?**

Typescript

**What did you expect to happen?**

`Process finished with exit code 0`

**What actually happened?**

```
prettier-eslint [ERROR]: prettier formatting failed due to a prettier error
prettier-eslint-cli [ERROR]: There was an error formatting "/Users/colhoop/Sources/UGP/tms/tms-frontend/custom.d.ts": 
    TypeError: Expected `input` to be a `string`, got `object`
        at module.exports (/Users/colhoop/Sources/UGP/tms/tms-frontend/node_modules/indent-string/index.js:11:9)
        at prettify (/Users/colhoop/Sources/UGP/tms/tms-frontend/node_modules/@prettier/eslint/dist/index.js:133:37)
        at format (/Users/colhoop/Sources/UGP/tms/tms-frontend/node_modules/@prettier/eslint/dist/index.js:113:20)
        at async /Users/colhoop/Sources/UGP/tms/tms-frontend/node_modules/prettier-eslint-cli/dist/format-files.js:255:26
```

**Environments:**

- Prettier Version: 3.0.2
- Running Prettier via: prettier-eslint-cli@7.1.0
- Runtime: Node.js v18.15.0
- Operating System: macOS
- Prettier plugins (if any): eslint-plugin-prettier@5.0.0

**Steps to reproduce:**

Run `prettier-eslint --write "$(pwd)/**/*.{js,jsx,ts,tsx}"`

**Comment by JounQin** [comment]
Unrelated repo.
