### ISSUE TITLE
Error: Unexpected key "meta" found.

### ISSUE THREAD

**Issue by JeromSar** [prettier/eslint-plugin-prettier#659]
**What version of `eslint` are you using?**
8.57.0

**What version of `prettier` are you using?**
3.2.5

**What version of `eslint-plugin-prettier` are you using?**
5.1.3

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```js
import eslintPluginPrettierRecommended from 'eslint-plugin-prettier'

export default [
  {
    files: ['src/**/*.ts']
  },
  eslintPluginPrettierRecommended,
]

```

**What source code are you linting?**
Simple Typescript hello world

**What did you expect to happen?**
Eslint success or pass.

**What actually happened?**
I got an error:

```
> npx eslint src


Oops! Something went wrong! :(

ESLint: 8.57.0

Error: Unexpected key "meta" found.
    at ObjectSchema.validate (C:\Users\xx\Desktop\xx\functions\node_modules\@humanwhocodes\object-schema\src\object-schema.js:270:23)   
    at C:\Users\xx\Desktop\xx\functions\node_modules\@humanwhocodes\object-schema\src\object-schema.js:239:18
    at Array.reduce (<anonymous>)
    at ObjectSchema.merge (C:\Users\xx\Desktop\xx\functions\node_modules\@humanwhocodes\object-schema\src\object-schema.js:237:24)      
    at C:\Users\xx\Desktop\xx\functions\node_modules\@humanwhocodes\config-array\api.js:935:42
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfig (C:\Users\xx\Desktop\xx\functions\node_modules\@humanwhocodes\config-array\api.js:934:39)
    at FlatConfigArray.isFileIgnored (C:\Users\xx\Desktop\xx\functions\node_modules\@humanwhocodes\config-array\api.js:962:15)
    at C:\Users\xx\Desktop\xx\functions\node_modules\eslint\lib\eslint\eslint-helpers.js:312:49
    at Array.reduce (<anonymous>)
```

**Comment by JounQin** [comment]
`eslint-plugin-prettier/recommended` is the config entry, `eslint-plugin-prettier` is the plugin entry.
