### ISSUE TITLE
Eslint v9 — Key "rules": Key "prettier/prettier": Could not find "prettier" in plugin "prettier".

### ISSUE THREAD

**Issue by movie4** [prettier/eslint-plugin-prettier#672]
Hello!
Thanks for the cool plugin - when running on the new version, it doesn’t work correctly

**What version of `eslint` are you using?**
eslint@9.7.0

**What version of `prettier` are you using?**
prettier@3.3.3

**What version of `eslint-plugin-prettier` are you using?**
eslint-plugin-prettier@5.2.1

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.eslintrc` files)**
```
const eslintJs = require('@eslint/js')
const eslintPluginPrettierRecommended = require('eslint-plugin-prettier/recommended');
const eslintReact = require('eslint-plugin-react')
const eslintTypeScript = require('typescript-eslint')

module.exports = [
  eslintJs.configs.recommended,
  ...eslintTypeScript.configs.recommended,
  {
    plugins: {
      react: eslintReact,
      prettier: eslintPluginPrettierRecommended.rules,
    },
  },
  {
    ignores: ['dist', 'node_modules', 'eslint.config.mjs'],
  },
  {
    files: ['**/*.{js,jsx,mjs,cjs,ts,tsx}'],
    rules: {
      ...eslintPluginPrettierRecommended.rules,
    }
  },
]

```

**What source code are you linting?**
TypeScript JSX

**What did you expect to happen?**
```
[Info  - 10:57:16] ESLint server is starting.
[Info  - 10:57:16] ESLint server running in node v20.9.0
[Info  - 10:57:16] ESLint server is running.
[Info  - 10:57:17] Server process exited successfully
[Info  - 10:57:19] ESLint library loaded from: /Volumes/node_modules/eslint/lib/api.js
[Error - 10:57:19] Calculating config file for file:///Volumes/src/components/Avatar/Avatar.interface.ts) failed.
TypeError: Key "rules": Key "prettier/prettier": Could not find "prettier" in plugin "prettier".
    at throwRuleNotFoundError (/Volumes/node_modules/eslint/lib/config/rule-validator.js:66:11)
    at RuleValidator.validate (/Volumes/node_modules/eslint/lib/config/rule-validator.js:147:17)
    at [finalizeConfig] (/Volumes/node_modules/eslint/lib/config/flat-config-array.js:378:23)
    at FlatConfigArray.getConfigWithStatus (/Volumes/node_modules/@eslint/config-array/dist/cjs/index.cjs:1102:55)
    at FlatConfigArray.getConfig (/Volumes/node_modules/@eslint/config-array/dist/cjs/index.cjs:1120:15)
    at ESLint.calculateConfigForFile (/Volumes/node_modules/eslint/lib/eslint/eslint.js:1187:24)
    at async ESLint.isPathIgnored (/Volumes/node_modules/eslint/lib/eslint/eslint.js:1209:24)
    at async /Users/User/.vscode/extensions/dbaeumer.vscode-eslint-3.0.10/server/out/eslintServer.js:1:24295
    at async Object.M [as withClass] (/Users/User/.vscode/extensions/dbaeumer.vscode-eslint-3.0.10/server/out/eslintServer.js:1:19807)
    at async O.then.m.validate (/Users/User/.vscode/extensions/dbaeumer.vscode-eslint-3.0.10/server/out/eslintServer.js:1:24255)
```

**Comment by BPScott** [comment]
You're not using the recommended configuration correctly: https://github.com/prettier/eslint-plugin-prettier?tab=readme-ov-file#configuration-new-eslintconfigjs.

I've not proven it but I'm suspect sure you should be doing:


```js
const eslintJs = require('@eslint/js')
const eslintPluginPrettierRecommended = require('eslint-plugin-prettier/recommended');
const eslintReact = require('eslint-plugin-react')
const eslintTypeScript = require('typescript-eslint')


module.exports = [
  eslintJs.configs.recommended,
  ...eslintTypeScript.configs.recommended,
  {
    plugins: {
      react: eslintReact,
    },
  },
  {
    files: ['**/*.{js,jsx,mjs,cjs,ts,tsx}'],
    ...eslintPluginPrettierRecommended,
  },
  {
    ignores: ['dist', 'node_modules', 'eslint.config.mjs'],
  },
];
```

**Comment by movie4** [comment]
@BPScott — hello!

Thanks for quick reply

Noe getting error

```AssertionError [ERR_ASSERTION]: Node must be provided when reporting error if location is not provided```


```
const eslintJs = require('@eslint/js')
const eslintPluginPrettierRecommended = require('eslint-plugin-prettier/recommended')
const eslintReact = require('eslint-plugin-react')
const eslintTypeScript = require('typescript-eslint')


module.exports = [
  eslintJs.configs.recommended,
  ...eslintTypeScript.configs.recommended,
  {
    plugins: {
      react: eslintReact,
    },
  },
  {
    ignores: ['dist', 'node_modules', 'eslint.config.mjs'],
  },
  {
    files: ['**/*.{js,jsx,mjs,cjs,ts,tsx}'],
  },
  eslintPluginPrettierRecommended
]
```
